### ISSUE TITLE
Standalone Python code that supports the inception5h.pb model?

### ISSUE THREAD

**Issue by ProGamerGov** [jnordberg/dreamcanvas#2]
The model used in this project creates some really nice looking hallucinations (not sure how much of a role the tiling plays in this), like the "houses and plants" layer. 

Is it possible to make a standalone Python version of this code that skips all the real time changes and Java stuff in favor of easier to use standalone Python scripts? Or do you know any tiled DeepDream code that will support the inception5h.pb model? It would be nice to simply plug in the desired input image, and output image size, along with the target layer, and then have your settings/tiling/parameters do the rest.

**Comment by ProGamerGov** [comment]
Ok, I think I might have something working: 

The script: https://gist.github.com/ProGamerGov/ce48b54508303b23c05d591eaa7c855f

**Edit:**

The code seems to handle different image sizes really well.

**Comment by ProGamerGov** [comment]
I have now created a fully standalone version of your tiled DeepDream code, for those who do not want to deal with JavaScript, and those who want a tiled version of DeepDream that can run on both the CPU, and GPU: https://github.com/ProGamerGov/Protobuf-Dreamer

Now, I wonder how easy it would be in order to create a way to make custom DeepDream hallucinations by letting people train a compatible .pb model on whatever images they like?

**Comment by jnordberg** [comment]
Nice! Love the layer list you made
